spring:
  #数据库连接配置
  datasource:
    #jdbc-url: jdbc:mysql://192.168.2.183:3306/core_v68?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    url: jdbc:mysql://192.168.2.182:3306/wethink_sharding_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&autoReconnect=true
    username: wethink_test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #-------------Hikari 连接池配置 --------------------------
    #-----更多配置可访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      ## 最小空闲连接数量,默认10 为了性能考虑，不建议设置此值
      minimum-idle: 10
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 1000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名字
      pool-name: Wethink Hikarl
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1